# Generated by Django 5.0.4 on 2024-04-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.CharField(null=True),
        ),
    ]
