# Generated by Django 5.0.4 on 2024-04-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_uuid_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='tbl_teachers',
        ),
    ]
