# Generated by Django 5.0.4 on 2024-04-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_enrollment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_id',
            field=models.PositiveIntegerField(default=411, unique=True),
            preserve_default=False,
        ),
    ]
