# Generated by Django 5.0.4 on 2024-04-18 07:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_enrollment_enrollment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
