# Generated by Django 5.0.4 on 2024-04-19 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_enrollment_enrollment_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrollment_uuid',
            new_name='uuid',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='tbl_enrollments',
        ),
    ]
