# Generated by Django 5.0.4 on 2024-04-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('subject_code', models.IntegerField()),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_description', models.CharField(max_length=200)),
            ],
        ),
    ]
