# Generated by Django 5.0.4 on 2024-04-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_id',
        ),
    ]
