# Generated by Django 5.0.4 on 2024-04-19 00:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_rename_subject_code_subject_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
