# Generated by Django 5.0.4 on 2024-04-19 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_uuid_alter_subject_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subject',
            table='tbl_subjects',
        ),
    ]
